### ISSUE TITLE
Not working in Directus v10.13.0

### ISSUE THREAD

**Issue by pedrofnts** [cmiteam/directus-extension-custom-search#4]
I've just installed the extension, it's enabled, but no Search Config interface is show for _search_config field (input/string).

![CleanShot 2024-07-04 at 16 11 48](https://github.com/cmiteam/directus-extension-custom-search/assets/63073772/f7bea3db-c63a-4577-a4e7-78b3a09480f6)

![CleanShot 2024-07-04 at 16 12 16](https://github.com/cmiteam/directus-extension-custom-search/assets/63073772/aebbaab6-8081-46ae-ae82-932739cf50cf)

![CleanShot 2024-07-04 at 16 13 06](https://github.com/cmiteam/directus-extension-custom-search/assets/63073772/deb9e297-e681-4ba4-a638-4b6fd89ab1b0)

**Comment by JoshTheDerf** [comment]
The field needs to be created as an `alias`, not as a `string`. You should be able to find it when creating from the "simple" view. Not sure it will show up in the advanced view.
